apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: y2b3jgkvr-python 
  janus-idp.io/tekton: y2b3jgkvr-python
  backstage.io/kubernetes-id: y2b3jgkvr-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y2b3jgkvr-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml